import { Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Toaster } from "react-hot-toast";

const outfitFont = Outfit({
 
  subsets: ["latin"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${outfitFont.className}  h-full antialiased`}
    >
      <body className="">
   <Navbar/>
     <Toaster position="top-center" />
       
       <main>  
        {children}

       </main>
        
       
       <Footer/>
      </body>
    </html>
  );
}
